# Generated by Django 4.2.14 on 2024-08-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apiendpoint",
            old_name="response_processor_class",
            new_name="postprocessor",
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="preprocessor",
            field=models.SlugField(
                blank=True, choices=[("default", "Default")], max_length=200, null=True
            ),
        ),
    ]
