# Generated by Django 4.2.14 on 2024-10-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_response_processor_class_apiendpoint_postprocessor_and_more'),
    ]

    operations = [
       # migrations.AddField(
        #    model_name='apiendpoint',
        #    name='endpoint_headers',
        #    field=models.JSONField(blank=True, default=dict, null=True),
       # ),
    ]
