# Generated by Django 4.2.14 on 2024-10-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0002_rename_response_processor_class_apiendpoint_postprocessor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apiendpoint",
            name="endpoint_custom_headers",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
