# Generated by Django 4.2.14 on 2024-10-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_apiendpoint_endpoint_custom_headers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiendpoint",
            name="endpoint_custom_headers",
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="endpoint_headers",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
