# Generated by Django 4.2.14 on 2024-10-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_apiendpoint_endpoint_headers'),
        ('services', '0004_remove_apiendpoint_endpoint_custom_headers_and_more'),
    ]

    operations = [
    ]
