# Generated by Django 4.2.14 on 2025-02-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_companysetting_key'),
        ('services', '0005_merge_20241022_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_service_endpoint', to='company.company', verbose_name='Company'),
        ),
    ]
