# Generated by Django 4.2.14 on 2024-08-12 12:31

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("master_assistant", "Master assistant"),
                            ("order_query_assistant", "Order queries assitant"),
                            (
                                "brand_onboarding_assistant",
                                "Brand onboarding assistant",
                            ),
                            ("bulk_order_assistant", "Bulk order assistant"),
                            ("corp_gifting_assistant", "Corporate gifting assistant"),
                            ("expert_assistant", "Expert assistant"),
                            ("agent_assistant", "Agent assistant"),
                            ("summary_assistant", "Summary assistant"),
                            ("actionables_assistant", "Actionables assistant"),
                            (
                                "sen_analysis_assistant",
                                "Sentimental analysis assistant",
                            ),
                            (
                                "profile_data_extracting_assistant",
                                "Profile data extraction assistant",
                            ),
                            ("agent_evaluation_prompt", "Agent evaluation prompt"),
                            ("brand_support_assistant", "Brand Support Assistant"),
                            ("policy_expert_assistant", "Policy Expert Assistant"),
                        ],
                        default="master_assistant",
                        max_length=100,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System prompt"),
                            ("assistant", "Assistant prompt"),
                            ("function", "Function prompt"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "llm",
                    models.CharField(
                        choices=[
                            ("openai", "Open AI"),
                            ("google", "Google"),
                            ("mistral", "Mistral"),
                        ],
                        default="openai",
                        max_length=30,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4-0125-preview", "GPT-4"),
                            ("gpt-3.5-turbo-1106", "GPT-3.5"),
                            ("gpt-4o", "GPT-4o"),
                            ("gemini-1", "Gemini-1"),
                            ("gemini-1.5", "Gemini-1.5"),
                        ],
                        default="gpt-4",
                        max_length=100,
                    ),
                ),
                ("content", models.TextField()),
                ("functions", models.JSONField(default=dict)),
                ("active", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.function"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="function",
            name="prompt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.prompt"
            ),
        ),
        migrations.CreateModel(
            name="Conversations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message_id",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                (
                    "parent_message_id",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("mobile", models.CharField(max_length=128)),
                ("role", models.CharField(default="user", max_length=20)),
                (
                    "function_name",
                    models.CharField(default=None, max_length=128, null=True),
                ),
                ("message", models.TextField()),
                ("session_type_id", models.IntegerField(default=0)),
                (
                    "session_id",
                    models.CharField(
                        default=chat.models.current_timestamp_as_int, max_length=256
                    ),
                ),
                ("client_session_ref_id", models.CharField(max_length=256, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "chat_conversations",
            },
        ),
    ]
