# Generated by Django 4.2.14 on 2024-08-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="llm",
            field=models.CharField(
                choices=[
                    ("openai", "Open AI"),
                    ("google", "Google"),
                    ("local", "Open Source"),
                ],
                default="openai",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-4-0125-preview", "GPT-4"),
                    ("gpt-3.5-turbo-1106", "GPT-3.5"),
                    ("gpt-4o", "GPT-4o"),
                    ("gemini-1", "Gemini-1"),
                    ("gemini-1.5", "Gemini-1.5"),
                    ("mistralai/Mistral-7B-Instruct-v0.3", "Mistral-7B-Instruct"),
                    ("microsoft/Phi-3-mini-4k-instruct", "Phi-3-Mini-4k-Instruct"),
                ],
                default="gpt-4",
                max_length=100,
            ),
        ),
    ]
