# Generated by Django 4.2.14 on 2024-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_prompt_llm_alter_prompt_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("master_assistant", "Master assistant"),
                    ("order_query_assistant", "Order queries assitant"),
                    ("brand_onboarding_assistant", "Brand onboarding assistant"),
                    ("bulk_order_assistant", "Bulk order assistant"),
                    ("corp_gifting_assistant", "Corporate gifting assistant"),
                    ("expert_assistant", "Expert assistant"),
                    ("agent_assistant", "Agent assistant"),
                    ("summary_assistant", "Summary assistant"),
                    ("actionables_assistant", "Actionables assistant"),
                    ("sen_analysis_assistant", "Sentimental analysis assistant"),
                    (
                        "profile_data_extracting_assistant",
                        "Profile data extraction assistant",
                    ),
                    ("agent_evaluation_prompt", "Agent evaluation prompt"),
                    ("brand_support_assistant", "Brand Support Assistant"),
                    ("policy_expert_assistant", "Policy Expert Assistant"),
                    ("survey_assistant", "Survey Assistant"),
                ],
                default="master_assistant",
                max_length=100,
            ),
        ),
    ]
