# Generated by Django 4.2.14 on 2024-08-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_prompt_prompt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangfusePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langfuse_secret_key', models.CharField(max_length=100)),
                ('langfuse_public_key', models.CharField(max_length=100)),
            ],
        ),
    ]
