# Generated by Django 4.2.14 on 2024-08-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_langfuseprompt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LangfusePrompt",
        ),
    ]
