# Generated by Django 4.2.14 on 2024-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_langfuseprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='message_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversations',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('pdf', 'PDF'), ('video', 'Video')], default='text', max_length=10),
        ),
    ]
