# Generated by Django 4.2.14 on 2024-11-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_conversations_message_metadata_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversations",
            old_name="client_session_ref_id",
            new_name="client_identifier",
        ),
        migrations.RemoveField(
            model_name="conversations",
            name="session_type_id",
        ),
        migrations.AddField(
            model_name="conversations",
            name="billing_session_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="conversations",
            name="request_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="conversations",
            name="request_medium",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("api", "API"),
                    ("python_sdk", "Python SDK"),
                    ("js_sdk", "JS SDK"),
                ],
                default="api",
            ),
        ),
    ]