# Generated by Django 4.2.14 on 2024-11-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0007_rename_client_session_ref_id_conversations_client_identifier_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversations",
            name="request_medium",
            field=models.CharField(default="api", max_length=128, null=True),
        ),
    ]

