# Generated by Django 4.2.14 on 2024-11-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_conversations_request_medium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversations",
            name="function_name",
            field=models.CharField(
                default=None, max_length=128, null=True, verbose_name="Function name"
            ),
        ),
        migrations.AlterField(
            model_name="conversations",
            name="request_medium",
            field=models.CharField(
                default="api", max_length=128, null=True, verbose_name="Request Medium"
            ),
        ),
        migrations.AlterField(
            model_name="conversations",
            name="role",
            field=models.CharField(default="user", max_length=20, verbose_name="Role"),
        ),
    ]
