# Generated by Django 4.2.14 on 2024-12-17 14:09

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_companysetting_key"),
        ("chat", "0009_alter_conversations_function_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("client_identifier", models.CharField(max_length=256, null=True)),
                (
                    "session_id",
                    models.CharField(
                        default=chat.models.current_timestamp_as_int, max_length=256
                    ),
                ),
                ("conv_summary", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Session",
                "verbose_name_plural": "Conversation Sessions",
                "db_table": "chat_conversation_sessions",
            },
        ),
    ]
