# Generated by Django 4.2.14 on 2024-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_conversationsessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversations",
            name="client_session_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="conversationsessions",
            name="client_session_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
