# Generated by Django 4.2.14 on 2024-12-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_companysetting_key"),
        ("chat", "0011_conversations_client_session_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConversationSessions",
            new_name="ConversationSession",
        ),
    ]
