# Generated by Django 4.2.14 on 2025-02-13 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_alter_companysetting_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0012_rename_conversationsessions_conversationsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowAttributes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        default=None, max_length=128, null=True, verbose_name="name"
                    ),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[("response_formatter", "Response Formatter")],
                        default="response_formatter",
                        max_length=50,
                    ),
                ),
                (
                    "response_formatter_type",
                    models.CharField(
                        blank=True,
                        choices=[("json", "JSON"), ("xml", "XML")],
                        max_length=50,
                        null=True,
                        verbose_name="Response Formatter Type",
                    ),
                ),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
