# Generated by Django 4.2.14 on 2025-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_companysetting_key'),
        ('chat', '0013_workflowattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowattributes',
            name='slug',
            field=models.SlugField(default=None, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='workflowattributes',
            unique_together={('company', 'slug')},
        ),
    ]
