# Generated by Django 4.2.14 on 2025-03-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0031_apicontroller_enabled_media_in_chat_history"),
        ("chat", "0014_workflowattributes_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="api_controller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api_controller.apicontroller",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="episodic_memory_created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="is_episodic_memory_created",
            field=models.BooleanField(default=False),
        ),
    ]
