# Generated by Django 4.2.14 on 2025-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_conversationsession_api_controller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='ignore_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='request_medium',
            field=models.CharField(default='api', max_length=128, null=True, verbose_name='Request Medium'),
        ),
    ]
