# Generated by Django 4.2.14 on 2025-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_conversationsession_ignore_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='ai_takeover_session',
            field=models.BooleanField(default=False),
        ),
    ]
