# Generated by Django 4.2.14 on 2025-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_conversationsession_ai_takeover_session"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversations",
            index=models.Index(fields=["company_id"], name="ix_conv_company_id"),
        ),
        migrations.AddIndex(
            model_name="conversations",
            index=models.Index(
                fields=["client_identifier"], name="ix_conv_client_identifier"
            ),
        ),
        migrations.AddIndex(
            model_name="conversations",
            index=models.Index(fields=["session_id"], name="ix_conv_session_id"),
        ),
        migrations.AddIndex(
            model_name="conversations",
            index=models.Index(
                fields=["session_id", "created_at"], name="ix_conv_sessidcreatedat"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["company_id"], name="ix_conv_session_company_id"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["client_identifier"], name="ix_conv_sess_client_identifier"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["company_id", "created_at"], name="ix_convsesscomidcreated_at"
            ),
        ),
    ]
