# Generated by Django 4.2.14 on 2024-08-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicontroller",
            name="api_route",
            field=models.SlugField(max_length=200),
        ),
    ]
