# Generated by Django 4.2.14 on 2024-08-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0002_alter_apicontroller_api_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="json_path",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
