# Generated by Django 4.2.14 on 2024-08-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0003_apicontroller_json_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicontroller",
            name="json_path",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
