# Generated by Django 4.2.14 on 2024-08-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0004_alter_apicontroller_json_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicontroller',
            options={'verbose_name': 'ApiController', 'verbose_name_plural': 'ApiController'},
        ),
    ]
