# Generated by Django 4.2.14 on 2024-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0004_alter_apicontroller_json_path"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apicontroller",
            options={
                "verbose_name": "ApiController",
                "verbose_name_plural": "ApiController",
            },
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("per_call_one_session", "Per Call One Session"),
                    ("time_based_session", "Time Based Session"),
                    ("token_based_session", "Token Based Session"),
                ],
                default="per_call_one_session",
                max_length=100,
            ),
        ),
    ]
