# Generated by Django 4.2.14 on 2024-08-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0005_alter_apicontroller_options'),
        ('api_controller', '0005_alter_apicontroller_options_and_more'),
    ]

    operations = [
    ]
