# Generated by Django 4.2.14 on 2024-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0006_alter_apicontroller_base_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicontroller",
            name="base_api_url",
            field=models.CharField(
                choices=[
                    (
                        "/api/v1/api-controller/invoke-service/",
                        "/api/v1/api-controller/invoke-service/",
                    )
                ],
                max_length=100,
            ),
        ),
    ]
