# Generated by Django 4.2.14 on 2024-08-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0006_merge_20240827_0825'),
        ('api_controller', '0007_alter_apicontroller_base_api_url'),
    ]

    operations = [
    ]
