# Generated by Django 4.2.14 on 2024-08-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0008_merge_20240828_1127"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
