# Generated by Django 4.2.14 on 2024-08-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0009_apicontroller_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="request_medium",
            field=models.CharField(
                blank=True,
                choices=[("whatsapp", "WhatsApp"), ("api", "API"), ("sdk", "SDK")],
                max_length=100,
            ),
        ),
    ]
