# Generated by Django 4.2.14 on 2024-08-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0010_apicontroller_request_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="application_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("batch_processing", "Batch Processing"),
                ],
                max_length=100,
            ),
        ),
    ]
