# Generated by Django 4.2.14 on 2024-09-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0008_merge_20240827_1318'),
        ('api_controller', '0011_apicontroller_application_type'),
    ]

    operations = [
    ]
