# Generated by Django 4.2.14 on 2024-09-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0012_merge_20240903_0622"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="required_parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
