# Generated by Django 4.2.14 on 2024-09-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0013_apicontroller_required_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="session_count",
            field=models.IntegerField(
                blank=True, help_text="Allowed Session Count at Once", null=True
            ),
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="session_time",
            field=models.IntegerField(
                blank=True,
                help_text="Allowed Session Time at Once, 'In Minutes'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apicontroller",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("per_call_one_session", "Per Call One Session"),
                    ("time_based_session", "Time Based Session"),
                    ("token_based_session", "Token Based Session"),
                    ("time_and_session_based_session", "Count and Time Based Session"),
                ],
                default="per_call_one_session",
                max_length=100,
            ),
        ),
    ]