# Generated by Django 4.2.14 on 2024-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0014_apicontroller_session_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicontroller",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("per_call_one_session", "Per Call One Session"),
                    ("time_based_session", "Time Based Session"),
                    ("token_based_session", "Token Based Session"),
                    ("time_and_count_based_session", "Count and Time Based Session"),
                ],
                default="per_call_one_session",
                max_length=100,
            ),
        ),
    ]
