# Generated by Django 4.2.14 on 2024-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0015_alter_apicontroller_session_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apicontroller",
            name="json_path",
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="graph_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
