# Generated by Django 4.2.14 on 2024-10-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0016_remove_apicontroller_json_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicontroller',
            name='workflow_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='default', max_length=100),
            preserve_default=False,
        ),
    ]
