# Generated by Django 4.2.14 on 2024-10-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0017_apicontroller_workflow_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="workflow_stream",
            field=models.BooleanField(default=False),
        ),
    ]
