# Generated by Django 4.2.14 on 2024-11-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0018_apicontroller_workflow_stream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicontroller",
            name="request_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("api", "API"),
                    ("python_sdk", "Python SDK"),
                    ("js_sdk", "JS SDK"),
                ],
                max_length=100,
            ),
        ),
    ]
