# Generated by Django 4.2.14 on 2024-11-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0019_alter_apicontroller_request_medium"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number associated with the worfkflow",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apicontroller",
            name="request_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp_meta", "Whatsapp Meta Cloud API"),
                    ("whatsapp_sinch", "Whatsapp Sinch API"),
                    ("api", "API"),
                    ("python_sdk", "Python SDK"),
                    ("js_sdk", "JS SDK"),
                ],
                max_length=100,
            ),
        ),
    ]
