# Generated by Django 4.2.14 on 2024-12-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0020_apicontroller_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="auth_credentials",
            field=models.JSONField(
                blank=True,
                help_text="Credentials associated with the phone number",
                null=True,
            ),
        ),
    ]
