# Generated by Django 4.2.14 on 2024-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0021_apicontroller_auth_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="conversation_session_count",
            field=models.IntegerField(
                blank=True,
                help_text="Specify the maximum number of messages allowed in a single conversation session. Enter '0' for unlimited messages.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="conversation_session_time",
            field=models.IntegerField(
                blank=True,
                help_text="Specify the maximum time allowed between messages in a single conversation session, measured in minutes.",
                null=True,
            ),
        ),
    ]
