# Generated by Django 4.2.14 on 2024-12-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0022_apicontroller_conversation_session_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apicontroller",
            old_name="session_count",
            new_name="billing_session_count",
        ),
        migrations.RenameField(
            model_name="apicontroller",
            old_name="session_time",
            new_name="billing_session_time",
        ),
        migrations.RenameField(
            model_name="apicontroller",
            old_name="session_type",
            new_name="billing_session_type",
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="conversation_session_refresh_keyword",
            field=models.CharField(
                blank=True,
                help_text="Keyword used to refresh context served to the LLM",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="conversation_session_type",
            field=models.CharField(
                choices=[
                    ("per_call_one_session", "Per Call One Session"),
                    ("time_based_session", "Time Based Session"),
                    ("token_based_session", "Token Based Session"),
                    ("time_and_count_based_session", "Count and Time Based Session"),
                ],
                default="time_based_conversation_session",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="apicontroller",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number associated with the worfkflow with country code, For Eg : '91XXXXXXXXXX'",
                max_length=20,
                null=True,
            ),
        ),
    ]
