# Generated by Django 4.2.14 on 2024-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_controller",
            "0023_rename_session_count_apicontroller_billing_session_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicontroller",
            name="conversation_session_refresh_keyword",
            field=models.CharField(
                blank=True,
                help_text="Enter a keyword or multiple comma-separated keywords (e.g. :  hello or hello, hi) that will trigger a context refresh for the LLM.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apicontroller",
            name="conversation_session_type",
            field=models.CharField(
                choices=[
                    (
                        "time_based_conversation_session",
                        "Time based conversation session",
                    ),
                    (
                        "count_based_conversation_session",
                        "Count based conversation session",
                    ),
                    (
                        "time_and_count_based_conversation_session",
                        "Time and Count based conversation session",
                    ),
                ],
                default="time_based_conversation_session",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="apicontroller",
            name="request_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp_meta", "Whatsapp Meta Cloud API"),
                    ("whatsapp_sinch", "Whatsapp Sinch API"),
                    ("twilio", "Twilio API"),
                    ("api", "API"),
                    ("python_sdk", "Python SDK"),
                    ("js_sdk", "JS SDK"),
                ],
                max_length=100,
            ),
        ),
    ]
