# Generated by Django 4.2.14 on 2024-12-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0024_apicontroller_tools_in_chat_history_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apicontroller",
            name="tools_in_chat_history",
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="enabled_tools_in_chat_history",
            field=models.BooleanField(
                default=False,
                help_text="Adds/Omits tool messages from chat history supplied to the LLM",
            ),
        ),
    ]
