# Generated by Django 4.2.14 on 2024-12-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0025_remove_apicontroller_tools_in_chat_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicontroller",
            name="enabled_tools_in_chat_history",
            field=models.BooleanField(
                default=False,
                help_text="Adds/Omits tool messages in chat history supplied to the LLM",
            ),
        ),
    ]
