# Generated by Django 4.2.14 on 2024-12-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_controller",
            "0024_alter_apicontroller_conversation_session_refresh_keyword_and_more",
        ),
        ("api_controller", "0026_alter_apicontroller_enabled_tools_in_chat_history"),
    ]

    operations = []
