# Generated by Django 4.2.14 on 2025-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0027_merge_20241224_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="enabled_summary_of_chat_history",
            field=models.BooleanField(
                default=False,
                help_text="Enable or disable the generation of a summary for chat history after a certain number of messages.",
            ),
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="messages_to_keep_in_chat_history_after_summarization",
            field=models.IntegerField(
                blank=True,
                help_text="The number of most recent messages to retain in chat history after summarization. Older messages will be removed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="summary_generation_trigger_limit",
            field=models.IntegerField(
                blank=True,
                help_text="The maximum number of messages allowed in chat history before generating a summary.",
                null=True,
            ),
        ),
    ]
