# Generated by Django 4.2.14 on 2025-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_controller",
            "0028_apicontroller_enabled_summary_of_chat_history_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="voice_assistant_interruption",
            field=models.BooleanField(
                default=True,
                help_text="Enable/Disable voice assistant interruption during AI is speaking",
            ),
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="voice_assistant_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("openai_realtime_api", "Openai Realtime API"),
                    ("workflow", "Workflow"),
                ],
                help_text="select method for voice assistant(workflow/openai_realtime_api)",
                max_length=100,
            ),
        ),
    ]
