# Generated by Django 4.2.14 on 2025-02-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_controller", "0029_apicontroller_voice_assistant_interruption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="enabled_long_term_memory_generation",
            field=models.BooleanField(
                default=False,
                help_text="Enable or disable the generation of long term memories",
            ),
        ),
        migrations.AddField(
            model_name="apicontroller",
            name="vector_storage_for_long_term_memory",
            field=models.CharField(
                choices=[("neo4j", "Neo4j"), ("qdrant", "Qdrant")],
                default="neo4j",
                help_text="Add credentials for accessing storage in company settings",
                max_length=100,
            ),
        ),
    ]
