# Generated by Django 4.2.14 on 2025-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_controller",
            "0030_apicontroller_enabled_long_term_memory_generation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apicontroller",
            name="enabled_media_in_chat_history",
            field=models.BooleanField(
                default=False,
                help_text=" Enables Images/documents etc to be stored as base 64 in Chat History Cache",
            ),
        ),
    ]
