# Generated by Django 4.2.14 on 2025-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0031_apicontroller_enabled_media_in_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicontroller',
            name='request_medium',
            field=models.CharField(blank=True, choices=[('whatsapp_meta', 'Whatsapp Meta Cloud API'), ('whatsapp_sinch', 'Whatsapp Sinch API'), ('twilio', 'Twilio API'), ('api', 'API'), ('python_sdk', 'Python SDK'), ('js_sdk', 'JS SDK'), ('waha', 'WAHA')], max_length=100),
        ),
    ]
