# Generated by Django 4.2.14 on 2025-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_controller', '0032_alter_apicontroller_request_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicontroller',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Phone number associated with the worfkflow with country code, For Eg : '91XXXXXXXXXX'", max_length=100, null=True),
        ),
    ]
