# Generated by Django 4.2.14 on 2025-04-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='data_source_creds',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
