ERROR_WHILE_SAVING = "ERROR WHILE SAVING"
ERROR_DATA_NOT_FOUND = "DATA NOT FOUND"
ERROR_INVALID_DATA = "INVALID DATA"
ERROR_INVALID_URL = "INVALID URL"
ERROR_URL_NOT_EXISTS = "URL NOT EXISTS"
ERROR_INVALID_TOKEN = "INVALID TOKEN"
ERROR_ENTER_DISTRICT = "Please Check The Data Does Not Have District Or State"
ERROR_INVALID_CRED = "INVALID CREDENTIAL"
ERROR_INVALID_METERING_CONFIG = "INVALID METERING CONFIG"
ERROR_MISSING_REQUIRED_PARAMS = 'MISSING_REQUIRED_PARAMS'
ERROR_API_ROUTE_NOT_FOUND = 'ERROR_API_ROUTE_NOT_FOUND'

MESSAGE_CREATED_SUCCESSFULLY = "Created Successfully"
MESSAGE_RUN_SUCCESSFULLY = "File Runned Successfully"
MESSAGE_ROI_NOT_GENERATED = "ROI is not generated for the Corresponding Devices"
MESSAGE_ENTER_DISTRICT = "Please Check The Data Does Not Have District Or State"
MESSAGE_REQUESTED_SUCCESSFULLY = "Requested Successfully"
MESSAGE_REJECTED_SUCCESSFULLY = "Rejected Successfully"
MESSAGE_VERIFIED_SUCCESSFULLY = "Verified Successfully"
MESSAGE_UPLOADED_SUCCESSFULLY = "Uploaded Successfully"
MESSAGE_MARKED_ACCIDENT_SUCCESSFULLY = "Marked Accident Successfully"
MESSAGE_UNMARKED_ACCIDENT_SUCCESSFULLY = "Unmarked Accident Successfully"
MESSAGE_DATA_NOT_FOUND = "DATA NOT FOUND"
MESSAGE_INVALID_DATA = "INVALID DATA"
MESSAGE_SAVED_SUCCESSFULLY = "MESSAGE SAVED SUCCESSFULLY"
MESSAGE_UPDATED_SUCCESSFULLY = "UPDATED SUCCESSFULLY"
MESSAGE_DELETED_SUCCESSFULLY = "DELETED SUCCESSFULLY"
MESSAGE_USERNAME_ALREADY_EXIST = "Username Already Exist"
MESSAGE_DEVICE_NAME_ALREADY_EXIST = "Device Name Already Exist"
MESSAGE_DEVICE_ID_ALREADY_EXIST = "Device ID Already Exist"
MESSAGE_SDK_DEVICE_ID_ALREADY_EXIST = "Device SDK ID Already Exist"
MESSAGE_IP_ADDRESS_ALREADY_EXIST = "Device IP ADDRESS Exist"
MESSAGE_URL_NOT_EXISTS = "Url Not Exists"
MESSAGE_MARKED_COMPLETED_SUCCESSFULLY = "Marked Completed Successfully"
MESSAGE_TOKEN_VERIFIED = "Token Verified"
MESSAGE_INVALID_TOKEN = "Invalid Verified"
MESSAGE_ADD_DATA_IN_ADMIN = "No Records Found for Selected Duration"
MESSAGE_SOMETHING_WENT_WRONG = "Something Went Wrong"
MESSAGE_INVALID_METERING_CONFIG = "Metering not configured properly."
MESSAGE_MISSING_REQUIRED_PARAMS = 'One or more required parameters are missing.'

#kafka return message
KAFKA_MESSAGE_QUEUE_CREATED = "Kafka Queue Created Successfully"

#error messages
MESSAGE_API_ROUTE_NOT_FOUND = 'Api Route Not Found'