# Generated by Django 4.2.14 on 2024-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyentity",
            name="desc",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
