# Generated by Django 4.2.14 on 2024-08-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_companyentity_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="langfuse_public_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="langfuse_secret_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
