# Generated by Django 4.2.14 on 2024-08-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_company_langfuse_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="current_env",
            field=models.CharField(
                blank=True, help_text="<env>_<company_name>", max_length=100, null=True
            ),
        ),
    ]
