# Generated by Django 4.2.14 on 2024-09-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_company_current_env"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="current_env",
            field=models.CharField(
                blank=True,
                help_text="<env>_<company_name>: Metering Subject",
                max_length=100,
                null=True,
            ),
        ),
    ]
