# Generated by Django 4.2.14 on 2024-09-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_company_langfuse_project_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="frontend_link",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Demo Link"
            ),
        ),
    ]
