# Generated by Django 4.2.14 on 2024-09-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_company_current_env"),
        ("company", "0006_company_frontend_link"),
    ]

    operations = []
