# Generated by Django 4.2.14 on 2024-09-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_merge_20240909_1202"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettingProxyModel",
            fields=[],
            options={
                "verbose_name": "Company Setting",
                "verbose_name_plural": "Company Setting",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("company.companysetting",),
        ),
    ]