# Generated by Django 4.2.14 on 2024-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_companysettingproxymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="comment",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]