# Generated by Django 4.2.14 on 2024-09-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0009_company_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="openmeter_secret_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
