# Generated by Django 4.2.14 on 2025-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0011_alter_companysetting_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companysetting",
            name="key",
            field=models.CharField(
                blank=True,
                choices=[
                    ("whatsapp_provider", "WhatsApp Provider"),
                    ("KG_neo4j", "Knowledge Graph Neo4j"),
                    ("SQL_DB", "Knowledge Base SQL"),
                    ("pinecone", "Pinecone"),
                    ("twillio_company_number", "Twillio Company Number"),
                    ("BQ_DB", "Knowledge Base Big Query"),
                ],
                max_length=100,
            ),
        ),
    ]
