# Generated by Django 4.2.14 on 2024-09-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeyProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Key',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dash.apikey',),
        ),
    ]
