# Generated by Django 4.2.14 on 2024-12-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_apikeyproxymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='grant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
