# Generated by Django 4.2.14 on 2024-12-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_apikey_expired_at_apikey_grant_apikey_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
