# Generated by Django 4.2.14 on 2025-02-24 12:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_companysetting_key'),
        ('custom_auth', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_open_meter_link', 'Custom: Can view OpenMeter Link'), ('can_view_graph_workflow', 'Custom: Can view Graph Workflow'), ('can_view_conversation_history', 'Custom: an view Conversation History'), ('can_view_api_keys', 'Custom: Can view API Keys'), ('can_view_data_processing_queue_view', 'Custom: Can view Data Processing Queues'), ('can_view_access_attempts_view', 'Custom: Can view Access Attempts'), ('can_view_blocked_users_view', 'Custom: Can view Blocked Users'), ('can_view_health_check_view', 'Custom: Can view Health Check View'), ('can_access_backend_custom_pages', 'Custom: Can access backend Custom Pages')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^\\+?\\d{7,15}$')])),
                ('email_id', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('request_id', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10)),
                ('is_otp_used', models.BooleanField(default=False)),
                ('access_attempts', models.IntegerField(default=0)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_otp', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTP',
                'db_table': 'custom_auth_otp',
            },
        ),
    ]
