# Generated by Django 4.2.14 on 2025-03-03 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationgroup_notification'),
        ('custom_auth', '0004_alter_user_options_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_notification_group',
            field=models.ManyToManyField(to='notifications.notificationgroup', verbose_name='Notification Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
