# Generated by Django 4.2.14 on 2025-03-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0005_user_user_notification_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_view_open_meter_link", "Custom: Can view OpenMeter Link"),
                    ("can_view_graph_workflow", "Custom: Can view Graph Workflow"),
                    (
                        "can_view_conversation_history",
                        "Custom: Can view Conversation History",
                    ),
                    ("can_view_api_keys", "Custom: Can view API Keys"),
                    (
                        "can_view_data_processing_queue_view",
                        "Custom: Can view Data Processing Queues",
                    ),
                    (
                        "can_view_access_attempts_view",
                        "Custom: Can view Access Attempts",
                    ),
                    ("can_view_blocked_users_view", "Custom: Can view Blocked Users"),
                    (
                        "can_view_health_check_view",
                        "Custom: Can view Health Check View",
                    ),
                    (
                        "can_access_backend_custom_pages",
                        "Custom: Can access backend Custom Pages",
                    ),
                ],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
