# Generated by Django 4.2.14 on 2025-03-07 08:41

import data_processing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0013_alter_companysetting_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataEnrichment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "input_file",
                    models.FileField(
                        upload_to=data_processing.models.upload_as_input_file
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        upload_to=data_processing.models.upload_as_output_file
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "llm_model",
                    models.CharField(
                        choices=[("mistral", "Mistral")],
                        default="mistral",
                        max_length=10,
                    ),
                ),
                ("batch_size", models.IntegerField(default=100)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Enrichment Request",
                "verbose_name_plural": "Data Enrichment Requests",
                "db_table": "data_processing_data_enrichment",
            },
        ),
    ]
