# Generated by Django 4.2.14 on 2025-03-07 09:05

import data_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "00001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataenrichment",
            name="completion_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dataenrichment",
            name="output_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=data_processing.models.upload_as_output_file,
            ),
        ),
    ]
