# Generated by Django 4.2.14 on 2025-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0002_dataenrichment_completion_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataenrichment",
            name="processing_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
