# Generated by Django 4.2.14 on 2025-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0003_dataenrichment_processing_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataenrichment",
            name="file_size",
            field=models.IntegerField(default=100, help_text="File Size In MB"),
        ),
        migrations.AlterField(
            model_name="dataenrichment",
            name="llm_model",
            field=models.CharField(
                choices=[("mistral", "Mistral")],
                default="mistral",
                max_length=10,
                verbose_name="LLM Model",
            ),
        ),
    ]
