# Generated by Django 4.2.14 on 2025-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0004_dataenrichment_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataenrichment",
            name="execution_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataenrichment",
            name="execution_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataenrichment",
            name="file_size",
            field=models.IntegerField(
                blank=True, help_text="File Size In MB", null=True
            ),
        ),
        migrations.AlterField(
            model_name="dataenrichment",
            name="prompt",
            field=models.CharField(max_length=200),
        ),
    ]
