# Generated by Django 4.2.14 on 2025-03-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0005_dataenrichment_execution_end_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dataenrichment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Data Enrichment Request",
                "verbose_name_plural": "Data Enrichment Requests",
            },
        ),
        migrations.AddField(
            model_name="dataenrichment",
            name="status_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dataenrichment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
