# Generated by Django 4.2.14 on 2025-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0006_alter_dataenrichment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataenrichment",
            name="name",
            field=models.CharField(
                default="Data Enrichment",
                help_text="Name of the Data Enrichment request",
                max_length=200,
                verbose_name="Name",
            ),
        ),
    ]
