# Generated by Django 4.2.14 on 2025-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0007_dataenrichment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataenrichment",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("ollama_mistral", "Ollama: Mistral"),
                    ("openai_gpt_3_5", "OpenAI: GPT-3.5"),
                    ("vertex_ai_mistral", "Vertex AI: Mistral"),
                ],
                default="ollama_mistral",
                max_length=30,
                verbose_name="LLM Model",
            ),
        ),
    ]
