# Generated by Django 4.2.14 on 2025-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0011_alter_dataenrichment_llm_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataenrichment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partition_created", "Partitions Created"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
