# Generated by Django 4.2.14 on 2025-03-19 05:59

import basics.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0013_alter_companysetting_key"),
        ("data_processing", "0013_dataingestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataingestion",
            name="session_id",
            field=models.CharField(
                blank=True,
                default=basics.utils.UUID.get_uuid,
                editable=False,
                help_text="Unique session identifier for this ingestion request",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="DataIngestionPartition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "input_file_path",
                    models.CharField(
                        help_text="Path to the input partition file", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Current status of the partition",
                        max_length=20,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this partition was processed",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Additional metadata about the partition",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        help_text="Data Ingestion request this partition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partitions",
                        to="data_processing.dataingestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Ingestion Partition",
                "verbose_name_plural": "Data Ingestion Partitions",
                "db_table": "data_processing_data_ingestion_partition",
                "ordering": ["created_at"],
            },
        ),
    ]
