# Generated by Django 4.2.14 on 2025-03-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_processing", "0014_dataingestion_session_id_dataingestionpartition"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataenrichment",
            name="combine_output_files",
            field=models.BooleanField(
                default=False, help_text="Combine output files into a single file"
            ),
        ),
        migrations.AddField(
            model_name="dataenrichment",
            name="parallel_threading_count",
            field=models.IntegerField(default=1),
        ),
    ]
