# Generated by Django 4.2.14 on 2025-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0015_dataenrichment_combine_output_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataingestion',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
