# Generated by Django 4.2.14 on 2025-04-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0016_alter_dataingestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataingestion',
            name='chunking_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('processing', 'Processing'), ('pending', 'Pending')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataingestion',
            name='chunk_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of objects/rows/tokens depending on file type', null=True),
        ),
        migrations.AlterField(
            model_name='dataingestion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ingestion_files/'),
        ),
    ]
